name: Build (nightly)

on:
  push:
    paths:
    - '.github/workflows/nightly.yml'
  workflow_run:
    workflows: ["Build, Test, and Benchmark"]
    branches: [master]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  auto-cancel:
    runs-on: Ubuntu-latest
    steps:
    - uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}

  build:
    needs: auto-cancel
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            ghc-ver: 8.10.2.2
            cabal-ver: 3.2
          - os: macos-latest
            ghc-ver: 8.10.2
            cabal-ver: 3.2
          - os: ubuntu-latest
            ghc-ver: 8.10.2
            cabal-ver: 3.2

    env:
      ARGS: "-O0 --ghc-options=-split-sections --enable-executable-stripping --enable-library-stripping --disable-executable-profiling --disable-library-profiling --disable-debug-info"
      LINUX_ARGS: "--enable-static --enable-executable-static"
      MACOS_ARGS: "--flags=enable-cluster-counting --extra-lib-dirs=/usr/local/opt/icu4c/lib --extra-include-dirs=/usr/local/opt/icu4c/include"
      WIN64_ARGS: ""
    outputs:
      sha: ${{ steps.vars.outputs.short-sha }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Check out the master branch
      uses: actions/checkout@v2
      with:
        ref: 'master'
    - name: Set up platform-dependent variables
      id: vars
      run: |
        short-sha=$(git rev-parse --short=7 HEAD)
        nightly="Agda-nightly-${short-sha}"

        echo ::set-output name=sha::${short-sha}
        echo ::set-output name=nightly::${nightly}

        if [[ "$OSTYPE" == "msys"* ]]; then
          echo "::set-output name=args::${ARGS} ${WIN64_ARGS}"
          filename="${nightly}-win64.zip"
          echo "::set-output name=filename::${filename}"
          echo "::set-output name=content-type::application/zip"
          echo "::set-output name=compress-cmd::7z a ${filename} ${nightly} -bb"
        elif [[ "$OSTYPE" == "darwin"* ]]; then
          echo "::set-output name=args::${ARGS} ${MACOS_ARGS}"
          filename="${nightly}-macOS.tar.xz"
          echo "::set-output name=filename::${filename}"
          echo "::set-output name=content-type::application/x-xz"
          echo "::set-output name=compress-cmd::tar -a -cvf ${filename} ${nightly}"
        elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
          echo "::set-output name=args::${ARGS} ${MACOS_ARGS}"
          filename="${nightly}-linux.tar.xz"
          echo "::set-output name=filename::${filename}"
          echo "::set-output name=content-type::application/x-xz"
          echo "::set-output name=compress-cmd::tar -a -cvf ${filename} ${nightly}"
          echo "::set-output name=args::${ARGS} ${LINUX_ARGS}"
        fi
    - name: Display build variables
      run: |
        echo nightly=${{ steps.vars.outputs.nightly }}
        echo ${{ steps.vars.outputs.compress-cmd }}
        echo ${{ steps.vars.outputs.filename }}
        echo ${{ steps.vars.outputs.content-type }}
        echo ${{ steps.vars.outputs.args }}

    - uses: haskell/actions/setup@v1
      id: setup-haskell
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: Configure the build plan
      run: |
        cabal configure ${{ steps.vars.outputs.args }}

    - uses: actions/cache@v2
      name: Cache dependencies
      id: cache
      with:
        path: |
          ${{ steps.setup-haskell.outputs.cabal-store }}
        # A unique cache is used for each stack.yaml.
        key: nightly-${{ runner.os }}-ghc-${{ matrix.ghc-ver }}-cabal-${{ hashFiles('**/plan.json') }}

    - name: Build dependencies
      if: ${{ !steps.cache.outputs.cache-hit }}
      run: cabal build exe:agda exe:agda-mode --only-dependencies -v0

    - name: Build Agda
      uses: nick-invision/retry@v2
      # Liang-Ting (2020-12-8):
      # Due to a ghc bug on Windows, it is necessary to build Agda twice (or more)
      # See:
      #   - https://github.com/agda/agda/issues/4543
      #   - https://gitlab.haskell.org/ghc/ghc/-/issues/18634
      with:
        max_attempts: 3
        timeout_minutes: 60
        retry_on: error
        command: cabal build exe:agda exe:agda-mode

    - name: Pack artefacts
      run: |
        mkdir -p ${{ steps.vars.outputs.nightly }}/bin
        cp -a src/data ${{ steps.vars.outputs.nightly }}

        if [[ "$OSTYPE" == "msys"* ]]; then
          find dist-newstyle/build -name '*.exe' -type f -exec cp {} ${{ steps.vars.outputs.nightly }}/bin \;
          cp -a .github/*.bat ${{ steps.vars.outputs.nightly }}
          C:/ProgramData/Chocolatey/bin/strip.exe ${{ steps.vars.outputs.nightly }}/bin/*
        else
          find dist-newstyle/build \( -name 'agda' -o -name 'agda-mode' \) -type f -exec cp {} ${{ steps.vars.outputs.nightly }}/bin \;
          cp -a .github/*.sh ${{ steps.vars.outputs.nightly }}
          strip ${{ steps.vars.outputs.nightly }}/bin/*
          if [[ "$OSTYPE" == "darwin"* ]]; then
            xattr -rc ${{ steps.vars.outputs.nightly }}/bin
          fi
        fi

        ${{ steps.vars.outputs.nightly }}/bin/agda --version
        ${{ steps.vars.outputs.compress-cmd }}

    - uses: actions/upload-artifact@v2
      with:
        path: ${{ steps.vars.outputs.filename }}
        name: ${{ steps.vars.outputs.filename }}
        if-no-files-found: error
        retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      TAG_NAME: nightly
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Delete the nightly tag if any
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        delete_release: true
        tag_name: ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Create a nightly release and upload artifacts as release assets
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        assets=()
        for asset in artifacts/**/*; do
          assets+=("-a" "$asset")
        done
        hub release create -p "${assets[@]}" -m "Nightly release (${{ needs.build.outputs.sha }})" ${{ env.TAG_NAME }}
